### ISSUE TITLE
如何划分ck+数据集的训练集和测试集？

### ISSUE THREAD

**Issue by nothingeasy** [HCPLab-SYSU/CD-FER-Benchmark#11]
据我了解，ck+数据集并没有划分验证集，怎么划分呢？ 做了交叉验证？

**Comment by putao537** [comment]
使用的是我们自己的划分标准，这个实验开始的比较久，我已经忘记是随机划分还是按照某个标准进行的划分了。
不过，全部的实验都是基于相同的数据集设置，所以论文中的数据是具有可比较性的。

**Comment by putao537** [comment]
> 据我了解，ck+数据集并没有划分验证集，怎么划分呢？ 做了交叉验证？

使用的是我们自己的划分标准，这个实验开始的比较久，我已经忘记是随机划分还是按照某个标准进行的划分了。
不过，全部的实验都是基于相同的数据集设置，所以论文中的数据是具有可比较性的。

**Comment by putao537** [comment]
> 据我了解，ck+数据集并没有划分验证集，怎么划分呢？ 做了交叉验证？

我们参照一定比例划分了训练集和验证集，最后得到的数据分布大致如下。
我们所有的实验都是再统一的数据集设置下进行的，论文中的实验结果具有可比性。
![Snipaste_2020-10-30_09-30-51](https://user-images.githubusercontent.com/22413761/97649561-9dcdf500-1a92-11eb-94b1-c154d2347fb3.png)
