### ISSUE TITLE
Not able to find image files in Datasets

### ISSUE THREAD

**Issue by meghbhalerao** [HCPLab-SYSU/CD-FER-Benchmark#12]
Hi Authors,
Thank you so much for making the code open source. However I am facing an issue with the **RAF/CK+** dataset. I downloaded the dataset from the [OneDrive](https://onedrive.live.com/?cid=f04a5473a61552b1&id=F04A5473A61552B1%21228&authkey=!AF0l9SVMG0bnSiY) Link as mentioned in the repository. I am **not able to find** any images in the **RAF dataset and CK+ dataset**. Kindly tell me where can I find the images corresponding to the dataset.
I look forward to your response.
Thanks again for your help,
Megh

**Comment by putao537** [comment]
Sorry for late reply. Due to the limitation of copyright, we can't share the images of other datasets but we can share the AFE dataset since we build this dataset. So, you should apply for  dataset by original page of each datasets, and then divide it according to the list we report.  

> Hi Authors,
> Thank you so much for making the code open source. However I am facing an issue with the **RAF/CK+** dataset. I downloaded the dataset from the [OneDrive](https://onedrive.live.com/?cid=f04a5473a61552b1&id=F04A5473A61552B1%21228&authkey=!AF0l9SVMG0bnSiY) Link as mentioned in the repository. I am **not able to find** any images in the **RAF dataset and CK+ dataset**. Kindly tell me where can I find the images corresponding to the dataset.
> I look forward to your response.
> Thanks again for your help,
> Megh

**Comment by meghbhalerao** [comment]
Thank you @putao537 and sorry for my late reply. I wanted to know if you share the AFE dataset with me? My email ID is megh.bhalerao@gmail.com.

Also, I wanted to know where can I find the format in which the images need to be present in so that they become compatible while running the code?

Thanks for your help,
Megh

**Comment by putao537** [comment]
> Thank you @putao537 and sorry for my late reply. I wanted to know if you share the AFE dataset with me? My email ID is [megh.bhalerao@gmail.com](mailto:megh.bhalerao@gmail.com).
> 
> Also, I wanted to know where can I find the format in which the images need to be present in so that they become compatible while running the code?
> 
> Thanks for your help,
> Megh

We have shared the AFE dataset in  in [Baidu Drive](https://pan.baidu.com/s/1d8szY1p1Js7gtbgV5Eg04Q) (password: c7xi) and [OneDrive](https://1drv.ms/u/s!ArFSFaZzVErwgWRdJfUlTBtG50om). To run the model on new  images, you should use MTCNN to compute the landmark of the new images which you can refer to code files in **devkit** folder in datasets link we have shared.
