### ISSUE TITLE
现有ICID代码，似乎只用了Source 训练集？

### ISSUE THREAD

**Issue by smwanghhh** [HCPLab-SYSU/CD-FER-Benchmark#14]
Source 选择AFED 数据集， Target使用 FER2013, backbone使用了ResNet18, 然而现有ICID的代码，似乎只用了Source训练集训练模型， Target 测试集准确率也只有38左右。而使用Source 和 Target 训练集一起训练模型时，Target测试集准确率达到了52.66。

**Comment by putao537** [comment]
您好，首先需要明确的是：在这个项目中，我们讨论的是 Cross Domain FER 任务，即只能使用 Source Domain 中的训练集与 Target Domain 中的训练集（需注意，Target Domain中的训练集的标签信息对于我们而言是未知的）。其次，在论文中我们所对比的算法里，LPL 和 ICID 属于标准的 FER 算法，对于未知标签数据无法处理，因此我们并未使用 Target Domain 中的训练集。最后，我们对比这两个算法的目的在于展示现有的 FER 算法在 Cross Domain FER 任务下的效果。
若无疑问，我将在不久后关闭此 Issue。随时欢迎交流。
