### ISSUE TITLE
CK+ dataset

### ISSUE THREAD

**Issue by cwwjyh** [HCPLab-SYSU/CD-FER-Benchmark#16]
你好，我下载您指定的数据集，发现CD-FER-Benchmark/Dataset/CK+/CK+_Emotion/Train/CK+_Train_crop/Angry文件夹下面是空的，没有数据，麻烦解答。谢谢

**Comment by putao537** [comment]
> 你好，我下载您指定的数据集，发现CD-FER-Benchmark/Dataset/CK+/CK+_Emotion/Train/CK+_Train_crop/Angry文件夹下面是空的，没有数据，麻烦解答。谢谢

这些数据集我们并没权限进行共享，需要自己去相应的数据集页面进行申请。
