### ISSUE TITLE
图卷积网络的邻接矩阵

### ISSUE THREAD

**Issue by lizoe** [HCPLab-SYSU/CD-FER-Benchmark#19]
你好，可以请问一下图卷积网络邻接矩阵的几个link值是根据什么确定的呢？
![image](https://user-images.githubusercontent.com/25115048/158593179-3aefc241-829b-43c2-933b-70f8d5e89fd8.png)
也就是代码中此位置的l几个link值是如何确定的呢？
非常感谢！

**Comment by putao537** [comment]
> 你好，可以请问一下图卷积网络邻接矩阵的几个link值是根据什么确定的呢？ ![image](https://user-images.githubusercontent.com/25115048/158593179-3aefc241-829b-43c2-933b-70f8d5e89fd8.png) 也就是代码中此位置的l几个link值是如何确定的呢？ 非常感谢！

抱歉，之前没看到这个 issue。
关于这几个值是如何选取的我忘记了，我们当时是对各种连接情况进行了划分，比如：同一领域中，global节点与local节点的连接是不同于local节点与local节点之间的连接的。
