### ISSUE TITLE
关于预训练模型的问题

### ISSUE THREAD

**Issue by liulian233** [HCPLab-SYSU/CD-FER-Benchmark#21]
您好，请问您提供的预训练模型中GCN网络的参数是和特征提取器、分类器、域鉴别器一起训练得到的吗，如果不是的话，具体是怎样得到的呢

**Comment by putao537** [comment]
您好，所有模型参数都是一起训练得到的。

**Comment by CHENSY-SIYU** [comment]
请问您有预训练模型吗，可以提供一份吗

**Comment by liulian233** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HCPLab-SYSU/CD-FER-Benchmark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 上午8:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HCPLab-SYSU/CD-FER-Benchmark] 关于预训练模型的问题 (Issue #21)





 
请问您有预训练模型吗，可以提供一份吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

backbone_IR_18_HeadFC_Softmax_112_512_1.0_Epoch_156_lfw_112_0.994_X4_112_0.990_agedb_30_112_0.949.pth (91.69M, 2022年08月07日 19:47 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=fb346438613e74c2686ff31d123803170201570e0d0b07094c0c025e0c15055956554901020055155351530b065b0109040d515e345d315a00570f5a5b56546728663b090c67795d0050227b6b6b5e5e155905406b09000a3e01550a6b091f083e71145757506e0954023b54524f6e0950063b081a01080c3e6c506705090367511a5d010467505f0450066707086e0950063b081a0105014f4410503405&code=a4d84818




MobileNetV2.pth (231.22M, 2022年08月07日 19:47 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=21393434c7e8bbc06c62a3111462051e540f030d0b07540748015657064f03075000190c0204021c0600060c035a5153070e5151326d377c0a5b5d58572c5245330b1a44460a370c&code=e9442b71




backbone_ir50_ms1m_epoch120.pth (166.39M, 2022年08月07日 19:48 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=36656238a6f9aac16b3ef51d4338011b56505a0c5d0900044f0406095015070300004f01070856190352015e5d0a03065b5c515d652733560306095a0a56566b0b1757083a5540050f3a07480a5b5b0550554c4811503309&code=beb8e834
