### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by qitingtingvi** [HCPLab-SYSU/CD-FER-Benchmark#22]
学者您好，在您提供的CD-FER-Benchmark开源代码中，有关数据集我有一处不明白，在Utils.py里面283行有这样一个路径'/RAF/basic/Annotation/Landmarks_5/，但是在公开数据集里都没有提供Landmarks_5，请问您是怎么生成的呢？或者你怎么制作的呢？可以把您的这几个数据集的Landmarks_5发给我一份吗？或者指导一下我怎么生成这个文件，希望您有空的时候帮助解答一下我的问题，万分感谢！！！

**Comment by putao537** [comment]
您好，正如我们在论文中所提及的那样，我们利用 MTCNN 对人脸图像进行预处理，从而得到人脸图像的 Landmark 文件。其中，我们选择五个人脸关键点，即“左眼，右眼，鼻尖，左嘴角，右嘴角”。
