### ISSUE TITLE
I can'T download pre-train models in Baidu Drive (password: tzrf) and OneDrive.

### ISSUE THREAD

**Issue by CHENSY-SIYU** [HCPLab-SYSU/CD-FER-Benchmark#23]
百度网盘的链接失效，OneDrive的文件损坏

**Comment by putao537** [comment]
> 百度网盘的链接失效，OneDrive的文件损坏
抱歉，之前上传到网盘后本地就没保留模型文件了。我建议使用 PyTorch 官方开源的预训练模型文件进行模型参数初始化，因为我们之前实验就是如此进行的。

**Comment by putao537** [comment]
> 百度网盘的链接失效，OneDrive的文件损坏

抱歉，之前上传到网盘后本地就没保留模型文件了。我建议使用 PyTorch 官方开源的预训练模型文件进行模型参数初始化，因为我们之前实验就是如此进行的。
