### ISSUE TITLE
训练模型问题

### ISSUE THREAD

**Issue by liulian233** [HCPLab-SYSU/CD-FER-Benchmark#24]
作者您好，请问可以提供已经训练好的，可以直接用于测试的AGRA模型吗，非常感谢！

**Comment by putao537** [comment]
> 作者您好，请问可以提供已经训练好的，可以直接用于测试的AGRA模型吗，非常感谢！

抱歉，由于论文中涉及的实验设置过多（即，三种模型结构，多种不同的源域/目标域数据集的选择），我们无法提供已经训练好的模型。
