### ISSUE TITLE
数据集如何处理

### ISSUE THREAD

**Issue by CHENSY-SIYU** [HCPLab-SYSU/CD-FER-Benchmark#25]
您好，我看了train的代码，想询问一下数据集具体是如何处理的（anno及下属文件夹等），AFE 的train_list.txt，以及各个数据集的list ，Oulu-CASIA用的是源数据集哪个文件夹的数据呢，如果可以的话，可以提供一下数据集处理相关的代码吗？

**Comment by putao537** [comment]
> 您好，我看了train的代码，想询问一下数据集具体是如何处理的（anno及下属文件夹等），AFE 的train_list.txt，以及各个数据集的list ，Oulu-CASIA用的是源数据集哪个文件夹的数据呢，如果可以的话，可以提供一下数据集处理相关的代码吗？

抱歉，这部分代码并没有保存，但是论文中有提及部分细节。
