### ISSUE TITLE
（打扰）关于快速得到表情识别结果的小问题：关于预训练模型

### ISSUE THREAD

**Issue by laoliu97** [HCPLab-SYSU/CD-FER-Benchmark#28]
您好，感谢您在学术上的贡献和开源代码
我想快速获得一个可以识别表情的项目，在阅读您的代码过程中发现您提供了预训练模型
所以想请问是否在完成Train on source doman后保存的模型才会拥有基本表情识别的能力？
还是加载您上传的预训练模型直接修改"TrainOnSourceDomain.py"进行test也会拥有一定的表情识别能力（只是准确率不够高）?
时间不太允许完成source doman 的训练再进行transfer,故提出这个比较蠢的疑问，十分感谢！

**Comment by putao537** [comment]
您好，正如论文所述，我们所使用的预训练模型是在大型人脸识别数据集上训练得到的，并不具有表情识别能力。
因此，您至少需要使用 Train_on_source_domain.py 对模型进行训练，才能使得模型具有表情识别能力。
但是，我认为您并不需要使用该项目，而是应该去寻找更适合您的小型人脸表情识别项目（例如：[WuJie1010/Facial-Expression-Recognition.Pytorch](https://github.com/WuJie1010/Facial-Expression-Recognition.Pytorch)，[xionghc/Facial-Expression-Recognition](https://github.com/xionghc/Facial-Expression-Recognition)）
如果仍有任何疑问，欢迎再次打开该 Issue。

> 您好，感谢您在学术上的贡献和开源代码 我想快速获得一个可以识别表情的项目，在阅读您的代码过程中发现您提供了预训练模型 所以想请问是否在完成Train on source doman后保存的模型才会拥有基本表情识别的能力？ 还是加载您上传的预训练模型直接修改"TrainOnSourceDomain.py"进行test也会拥有一定的表情识别能力（只是准确率不够高）? 时间不太允许完成source doman 的训练再进行transfer,故提出这个比较蠢的疑问，十分感谢！

**Comment by laoliu97** [comment]
> 您好，正如论文所述，我们所使用的预训练模型是在大型人脸识别数据集上训练得到的，并不具有表情识别能力。 因此，您至少需要使用 Train_on_source_domain.py 对模型进行训练，才能使得模型具有表情识别能力。 但是，我认为您并不需要使用该项目，而是应该去寻找更适合您的小型人脸表情识别项目（例如：[WuJie1010/Facial-Expression-Recognition.Pytorch](https://github.com/WuJie1010/Facial-Expression-Recognition.Pytorch)，[xionghc/Facial-Expression-Recognition](https://github.com/xionghc/Facial-Expression-Recognition)） 如果仍有任何疑问，欢迎再次打开该 Issue。
> 
> > 您好，感谢您在学术上的贡献和开源代码 我想快速获得一个可以识别表情的项目，在阅读您的代码过程中发现您提供了预训练模型 所以想请问是否在完成Train on source doman后保存的模型才会拥有基本表情识别的能力？ 还是加载您上传的预训练模型直接修改"TrainOnSourceDomain.py"进行test也会拥有一定的表情识别能力（只是准确率不够高）? 时间不太允许完成source doman 的训练再进行transfer,故提出这个比较蠢的疑问，十分感谢！

十分感谢！这是我第一次真正意义上得到作者的issue回复，同时很感激您能提供其他项目作为参考！

确实通过后续的阅读发现模型训练过程中也需要同时输入图像以及landmark,如您所说我还不太适合使用您的项目。

衷心感谢您在我个人的特殊阶段带来意外的温暖，祝好！
